SHOPEE_PARTNER_ID=2033681
SHOPEE_PARTNER_KEY=shpk4a6252796a70685050567067776267416d6168655744716772694f4c794c
SHOPEE_ACCESS_TOKEN=eyJhbGciOiJIUzI1NiJ9.CJGQfBABGMXtu30gASilo4nQBjDA38_gAzgBQAFICQ.eqZnjm_1OwRwnG6d-dmmnZbA_eViVSVDwyzezSTKavY
SHOPEE_REFRESH_TOKEN=eyJhbGciOiJIUzI1NiJ9.CJGQfBABGMXtu30gAiilo4nQBjDgxsCpBzgBQAFICQ.hYleTxaqtaBTWEXllTsuSCfPIO6__MmQTJpNPzNOfA8
SHOPEE_SHOP_ID=263124677
GEMINI_API_KEY=AIzaSyD7oyFQH9yDt5OseJNQCk-EfPB9GI7U8Aw
GROQ_API_KEY=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
REMOVEBG_API_KEY=uR5hpq8JQN5PxFoGmeHjuEsY
SERVER_BASE_URL=https://unpaining-transcriptionally-patrick.ngrok-free.dev
CLOUDINARY_CLOUD_NAME=dcudjmopb
CLOUDINARY_API_KEY=155269687562979
CLOUDINARY_API_SECRET=2cY-BoGl30u2DruWAsBthZuePlE
android.useAndroidX=true
android.nonTransitiveRClass=true
android.disallowKotlinSourceSets=false
org.gradle.jvmargs=-Xmx4g -XX:MaxMetaspaceSize=1g
